config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get 'orders/send_email_with_orders',
      to: 'orders#send_email_with_orders',
      as: :send_orders_mail
  get 'orders/generate_orders_pdf',
      to: 'orders#generate_orders_pdf',
      as: :generate_orders_pdf
  get 'feedback', to: 'home#feedback_mail', as: :feedback
  post '', to: 'home#feedback_mail', as: '/'
  root to: 'home#index'
  get '/about', to: 'home#about', as: :about
  resources :affiliates, only: %i[show index]
  resources :orders

  namespace :admin do
    get 'dashboard/index'
    get '', to: 'dashboard#index', as: '/'
    resources :users
    resources :affiliates do
      get 'show_workers',
          to: 'affiliates#show_workers',
          as: :show_workers
    end
    resources :taxes, except: :show
    get 'taxes/default_tax_selection', to: 'taxes#default_tax_selection',
                                       as: :default_tax_selection
    post 'taxes/set_default', to: 'taxes#set_default',
                              as: :set_default_tax_post
    resources :cars
    resources :user, controller: 'admin/users'
    resources :order_statuses, only: [:index]
    resources :orders do
      resources :invoices, only: %i[new create edit update]
      resource :car_assignment, only: %i[new create edit update]
    end
  end
  match '*path', to: 'home#routing_error', via: %i[get post put delete]
end

app/models/order.rb
# Order model class
class Order < Sequel::Model
  many_to_one :car
  many_to_one :tax
  many_to_one :user # , -> { where role: 'client' }, optional: true
  one_to_one :invoice

  STATUSES = [
    NEW = 'New'.freeze,
    IN_PROGRESS = 'In progress'.freeze,
    COMPLETED = 'Completed'.freeze
  ].freeze

  # scope :search_by_client_phone, ->(desired_phone) do where('client_phone LIKE ?', "%#{desired_phone}%").order('order_status ASC') end
end

app/controllers/admin/orders_controller.rb
module Admin
  #
  class OrdersController < AdminController
    respond_to :js
    def index
      result = Admin::Order::Index.call(params: params,
                                        current_user: current_user)
      handle_successful(result)
    end

    def new
      result = Admin::Order::Create::Present.call(params: params,
                                                  current_user: current_user)
      handle_successful(result)
    end

    def create
      result = Admin::Order::Create.call(params: params,
                                         current_user: current_user)
      handle_successful(result) do
        redirect_to admin_orders_path, notice: t('order_created')
      end

      handle_invalid(result) do
        render :new
      end
    end

    def show
      result = Admin::Order::Show.call(params: params,
                                       current_user: current_user)
      handle_successful(result)
    end

    def edit
      result = Admin::Order::Update::Present.call(params: params,
                                                  current_user: current_user)
      handle_successful(result)
    end

    def update
      result = Admin::Order::Update.call(params: params,
                                         current_user: current_user)
      handle_successful(result) do
        redirect_to admin_orders_path, notice: t('order_updated')
      end

      handle_invalid(result) do
        render :edit
      end
    end

    def destroy
      result = Admin::Order::Delete.call(params: params,
                                         current_user: current_user)
      handle_successful(result) do
        redirect_to admin_orders_path, notice: t('order_destroyed')
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include Matcher
  respond_to :js
  before_action :authenticate_user!, except: %i[new create]

  def index
    run Order::Index, params: params, current_user: current_user
  end

  def new
    result = Order::Create::Present.call(params: params)
    handle_successful(result)
  end

  def create
    result = Order::Create.call(params: params,
                                current_user: current_user)
    handle_successful(result) do
      redirect_to root_path, notice: t('order_created')
    end
    handle_invalid(result) do
      render :new
    end
  end

  def show
    result = Order::Show.call(params: params,
                              current_user: current_user)
    handle_successful(result)
  end

  def edit
    result = Order::Update::Present.call(params: params,
                                         current_user: current_user)
    handle_successful(result)
  end

  def update
    result = Order::Update.call(params: params,
                                current_user: current_user)
    handle_successful(result) do
      redirect_to orders_path(@model.id), notice: t('order_updated')
    end
    handle_invalid(result) do
      render :edit
    end
  end

  def destroy
    result = Order::Delete.call(params: params,
                                current_user: current_user)
    handle_successful(result) do
      flash[:notice] = t('order_destroyed')
    end
  end

  def send_email_with_orders
    result = Order::SendEmailWithOrders.call(params: params,
                                             current_user: current_user)
    handle_successful(result) do
      redirect_to orders_path, notice: t('order_sent')
    end
  end

  def generate_orders_pdf
    result = Order::GeneratePdfWithOrders.call(params: params,
                                               current_user: current_user)
    handle_successful(result) do
      render pdf: 'generate_orders_pdf.pdf.haml'
    end
  end
end

app/views/admin/orders/_form.html.haml
- if @form.errors.any?
  .error
    %h5.text-center
      = t('error')
      - @form.errors.full_messages.each do |message|
        %h6.text-center
          &#9899; #{message}


= form_for [:admin, @model] do |form|
  .row.justify-content-md-center.text-center
    .col-md-4
      .order_form_area
        .form-group
          = form.label :name
          = form.text_field :client_name, class: 'form-control'
        .form-group
          = form.label :phone
          .input-group
            %span.input-group-text +375
            = form.text_field :client_phone, placeholder: '25-123-45-67', class: 'form-control'
        .form-group
          = form.label :start_point
          = form.text_field :start_point, class: 'form-control'
        .form-group
          = form.label :end_point
          = form.text_field :end_point, class: 'form-control'
        .form-group
          = form.label t('activerecord.models.tax')
          = form.collection_select :tax_id, Tax.all, :id, :name, {prompt: false}, class: 'form-control'
        .actions
          = form.submit t('submit'), class: 'btn btn-primary'
          = link_to t('back'), admin_orders_path, class: 'btn btn-secondary'

app/views/admin/orders/_orders.html.haml
%table.table
  %thead.thead-inverse
    %tr
      %th #
      %th
        = t('activerecord.attributes.order.name')
      %th
        = t('activerecord.attributes.order.phone')
      %th
        = t('activerecord.models.order_status')
      %th
        = t('car')
      %th
        = t('activerecord.models.invoice')
      %th
  %tbody
    - for order in @model
      %tr{id: "order-#{order.id}"}
        %th
          = order.id
        %th
          = order.client_name
        %th
          +375-#{order.client_phone}
        %th
          = t("order_status.#{order.order_status}")
        %th
          - if order.car.nil? && current_user.role == :driver
            = link_to 'Взять заказ', driver_admin_order_car_assignment_path(order.id), method: :post, class: 'btn btn-primary btn-sm'
            %th
          - elsif order.car.nil?
            = link_to t('assign_car'), new_admin_order_car_assignment_path(order.id), class: 'btn btn-primary btn-sm'
            %th
          - else
            - if current_user.role != :driver && order.invoice.nil?
              =link_to "#{order.car.brand} #{order.car.car_model}, #{order.car.reg_number}", edit_admin_order_car_assignment_path(order.id)
              - unless order.invoice.nil?
                - if order.invoice.invoice_status == :paid
                  %th
                    #{order.invoice.total_price}
                    %div/
                    (#{t("invoice_status.#{order.invoice.invoice_status}")})
                - else
                  %th
                    #{link_to order.invoice.total_price, edit_admin_order_invoice_path(order, order.invoice)}
                    %div/
                    (#{t("invoice_status.#{order.invoice.invoice_status}")})
              - else
                %th
                  = link_to t('add_invoice'), new_admin_order_invoice_path(order.id), class: 'btn btn-primary btn-sm'
            - else
              #{order.car.brand} #{order.car.car_model}, #{order.car.reg_number}
              - unless order.invoice.nil?
                - if order.invoice.invoice_status == 'Paid'
                  %th
                    #{order.invoice.total_price}
                    %div/
                    (#{t("invoice_status.#{order.invoice.invoice_status}")})
                - else
                  %th
                    #{link_to order.invoice.total_price, edit_admin_order_invoice_path(order, order.invoice)}
                    %div/
                    (#{t("invoice_status.#{order.invoice.invoice_status}")})
              - else
                %th
                  = link_to t('add_invoice'), new_admin_order_invoice_path(order.id), class: 'btn btn-primary btn-sm'

        %th
          = link_to t('order_info'), admin_order_path(order.id), class: 'btn btn-outline-primary btn-sm'
          - unless current_user.role == 'driver'
            = link_to t('delete'), admin_order_path(order), method: :delete, data: { confirm: t('confirmation') }, class: 'btn btn-outline-danger btn-sm'

app/views/admin/orders/edit.html.haml
%h2.text-center
  = t('edit_order')

= render 'form', order: @model

app/views/admin/orders/index.html.haml
%h1.text-center
  = t('orders')
  %h5.text-center#notice= notice
  %h5.text-center.error#alert= alert
  = link_to t('new_order'), new_admin_order_path, class: 'btn btn-outline-success pull-right'
.row
  .col-sm-4
    = form_tag(admin_orders_path, method: :get, id: 'orders_search') do
      .input-group
        = text_field_tag :desired_phone, params[:desired_phone], {class: 'form-control', placeholder: t('search_order')}
        %span.input-group-btn
          = submit_tag t('search'), name: nil, class: 'btn btn-secondary'
.row
  .col-sm-12
    #orders= render 'orders'

app/views/admin/orders/index.js.haml
$("#orders").html("#{escape_javascript(render 'orders')}");

app/views/admin/orders/new.html.haml
%h2.text-center
  = t('new_order')

= render 'form', order: @model

app/views/admin/orders/show.html.haml
.row.justify-content-md-center.text-center
  .col-sm-4
    %h2
      #{t('order_number')}:
      = @model.id
    %ul.list-group
      %li.list-group-item
        %b
          #{t('activerecord.attributes.order.name')}:
        = @model.client_name
      %li.list-group-item
        %b
          #{t('activerecord.attributes.order.phone')}:
        +375-#{@model.client_phone}
      %li.list-group-item
        %b
          #{t('activerecord.attributes.order.start_point')}:
        = @model.start_point
      %li.list-group-item
        %b
          #{t('activerecord.attributes.order.end_point')}:
        = @model.end_point
      %li.list-group-item
        %b
          #{t('activerecord.models.tax')}:
        = @model.tax.nil? ? 'Укажите тариф.' : @model.tax.name
      -unless @model.car.nil?
        %li.list-group-item
          %b
            #{t('car')}:
          #{@model.car.brand} #{@model.car.car_model}, #{@model.car.reg_number}
      -else 
        %li.list-group-item
          = link_to t('assign_car'), new_admin_order_car_assignment_path(@model.id), class: 'btn btn-primary btn-sm'
      -unless @model.order_status.nil?
        %li.list-group-item
          %b
            #{t('status')}:
          = t("order_status.#{@model.order_status}")
      -unless @model.invoice.nil?
        %li.list-group-item
          %b
            #{t('activerecord.models.invoice')}:
          #{@model.invoice.total_price} (#{t('indebtedness')}: #{@model.invoice.indebtedness})
          %div/
          (#{t("invoice_status.#{@model.invoice.invoice_status}")})
      -else
        - if @model.car_id
          = link_to t('add_invoice'), new_admin_order_invoice_path(@model.id), class: 'btn btn-outline-success btn-sm'
        = link_to t('edit'), edit_admin_order_path(@model.id), style: 'float: right', class: 'btn btn-outline-primary btn-sm'
        - if current_user.role != 'driver'
          = link_to t('delete'), admin_order_path(@model), method: :delete, data: { confirm: t('confirmation') }, style: 'float: right', class: 'btn btn-outline-danger btn-sm'