config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get 'orders/send_email_with_orders',
      to: 'orders#send_email_with_orders',
      as: :send_orders_mail
  get 'orders/generate_orders_pdf',
      to: 'orders#generate_orders_pdf',
      as: :generate_orders_pdf
  get 'feedback', to: 'home#feedback_mail', as: :feedback
  post '', to: 'home#feedback_mail', as: '/'
  root to: 'home#index'
  get '/about', to: 'home#about', as: :about
  resources :affiliates, only: %i[show index]
  resources :orders

  namespace :admin do
    get 'dashboard/index'
    get '', to: 'dashboard#index', as: '/'
    resources :users
    resources :affiliates do
      get 'show_workers',
          to: 'affiliates#show_workers',
          as: :show_workers
    end
    resources :taxes, except: :show
    get 'taxes/default_tax_selection', to: 'taxes#default_tax_selection',
                                       as: :default_tax_selection
    post 'taxes/set_default', to: 'taxes#set_default',
                              as: :set_default_tax_post
    resources :cars
    resources :user, controller: 'admin/users'
    resources :order_statuses, only: [:index]
    resources :orders do
      resources :invoices, only: %i[new create edit update]
      resource :car_assignment, only: %i[new create edit update]
    end
  end
  match '*path', to: 'home#routing_error', via: %i[get post put delete]
end

app/models/order.rb
# Order model class
class Order < Sequel::Model
  many_to_one :car
  many_to_one :tax
  many_to_one :user # , -> { where role: 'client' }, optional: true
  one_to_one :invoice

  STATUSES = [
    NEW = 'New'.freeze,
    IN_PROGRESS = 'In progress'.freeze,
    COMPLETED = 'Completed'.freeze
  ].freeze

  # scope :search_by_client_phone, ->(desired_phone) do where('client_phone LIKE ?', "%#{desired_phone}%").order('order_status ASC') end
end

app/controllers/admin/orders_controller.rb
module Admin
  #
  class OrdersController < AdminController
    respond_to :js
    def index
      result = Admin::Order::Index.call(params: params,
                                        current_user: current_user)
      handle_successful(result)
    end

    def new
      result = Admin::Order::Create::Present.call(params: params,
                                                  current_user: current_user)
      handle_successful(result)
    end

    def create
      result = Admin::Order::Create.call(params: params,
                                         current_user: current_user)
      handle_successful(result) do
        redirect_to admin_orders_path, notice: t('order_created')
      end

      handle_invalid(result) do
        render :new
      end
    end

    def show
      result = Admin::Order::Show.call(params: params,
                                       current_user: current_user)
      handle_successful(result)
    end

    def edit
      result = Admin::Order::Update::Present.call(params: params,
                                                  current_user: current_user)
      handle_successful(result)
    end

    def update
      result = Admin::Order::Update.call(params: params,
                                         current_user: current_user)
      handle_successful(result) do
        redirect_to admin_orders_path, notice: t('order_updated')
      end

      handle_invalid(result) do
        render :edit
      end
    end

    def destroy
      result = Admin::Order::Delete.call(params: params,
                                         current_user: current_user)
      handle_successful(result) do
        redirect_to admin_orders_path, notice: t('order_destroyed')
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include Matcher
  respond_to :js
  before_action :authenticate_user!, except: %i[new create]

  def index
    run Order::Index, params: params, current_user: current_user
  end

  def new
    result = Order::Create::Present.call(params: params)
    handle_successful(result)
  end

  def create
    result = Order::Create.call(params: params,
                                current_user: current_user)
    handle_successful(result) do
      redirect_to root_path, notice: t('order_created')
    end
    handle_invalid(result) do
      render :new
    end
  end

  def show
    result = Order::Show.call(params: params,
                              current_user: current_user)
    handle_successful(result)
  end

  def edit
    result = Order::Update::Present.call(params: params,
                                         current_user: current_user)
    handle_successful(result)
  end

  def update
    result = Order::Update.call(params: params,
                                current_user: current_user)
    handle_successful(result) do
      redirect_to orders_path(@model.id), notice: t('order_updated')
    end
    handle_invalid(result) do
      render :edit
    end
  end

  def destroy
    result = Order::Delete.call(params: params,
                                current_user: current_user)
    handle_successful(result) do
      flash[:notice] = t('order_destroyed')
    end
  end

  def send_email_with_orders
    result = Order::SendEmailWithOrders.call(params: params,
                                             current_user: current_user)
    handle_successful(result) do
      redirect_to orders_path, notice: t('order_sent')
    end
  end

  def generate_orders_pdf
    result = Order::GeneratePdfWithOrders.call(params: params,
                                               current_user: current_user)
    handle_successful(result) do
      render pdf: 'generate_orders_pdf.pdf.haml'
    end
  end
end

app/views/orders/_form.html.haml
- if @form.errors.any?
  .error
    %h5
      = t('error_order')
      - @form.errors.full_messages.each do |message|
        %h6
          &#9899; #{message}
.row.justify-content-md-center
  .col-md-4
    .order_form_area
    = form_for @model do |form|
      -if user_signed_in?
        .form-group
          = form.text_field :client_name, placeholder: t('name'),
                            class: 'form-control', value: current_user.first_name
      -else
        .form-group
          = form.text_field :client_name, placeholder: t('name'), class: 'form-control'
      -if user_signed_in?
        .form-group
          .input-group
            %span.input-group-text +375
            = form.text_field :client_phone, placeholder: '25-123-45-67',
                              class: 'input-group form-control', value: current_user.phone
      -else
        .form-group
          .input-group
            %span.input-group-text +375
            = form.text_field :client_phone, placeholder: '25-123-45-67',
                              class: 'input-group form-control'
      .form-group
        = form.text_field :start_point, placeholder: "#{t('start_point_new')}", class: 'form-control'
      .form-group
        = form.text_field :end_point, placeholder: "#{t('end_point_new')}", class: 'form-control'
      .actions
        = form.submit t('submit'), class: 'btn btn-primary'
        = link_to t('back'), root_path, class: 'btn btn-secondary'

app/views/orders/_orders.html.haml
%section
  .container
    %table.table.orders_table
      %thead.thead-inverse
        %tr
          %th #
          %th
            = t('activerecord.attributes.order.name')
          %th
            = t('activerecord.attributes.order.phone')
          %th
            = t('activerecord.attributes.order.start_point')
          %th
            = t('activerecord.attributes.order.end_point')
          %th
      %tbody
        - for order in @model
          - cache order do
            %tr{id: "order-#{order.id}"}
              %th
                = link_to order.id, order_path(order.id)
              %th
                = order.client_name
              %th
                +375-#{order.client_phone}
              %th
                = order.start_point
              %th
                = order.end_point
              %th
                = link_to t('delete'), order, method: :delete, remote: true, data: { confirm: t('confirmation') }, class: 'btn btn-outline-danger btn-sm floating'
                = link_to t('edit'), edit_order_path(order.id), class: 'btn btn-outline-success btn-sm floating'

app/views/orders/destroy.js.haml
// Remove the deleted item from the table.
$("#order-#{@model.id}").remove();
$("#notice").html("#{flash[:notice]}");
//setTimeout(function() $("#notice").append(''), 2500);

app/views/orders/edit.html.haml
%section.client_order.sessions-new
  .text-center
    .container
      %h2.order-pad-top
        = t('edit_order')
      = render 'form', order: @order
%footer.text-center.footer-order
  .footer-top
    .container
      .row
        .footer-col.col-md-6
          %h6
            = link_to t('affiliates'), affiliates_path
        .footer-col.col-md-6
          %h6
            = link_to t('about_us'),about_path
  .footer-below
    .container
      .row
        .col-md-12
          = t('rights')

app/views/orders/generate_orders_pdf.pdf.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
    = wicked_pdf_stylesheet_link_tag 'pdf'
  %body
    %h1
      = t('orders_report')
    %h3.color-text
      = t('greeting', user_first_name: current_user.first_name,
                      user_last_name: current_user.last_name)
    %table
      %thead
        %tr.head
          %th #
          %th
            = t('activerecord.attributes.order.name')
          %th
            = t('activerecord.attributes.order.phone')
          %th
            = t('activerecord.attributes.order.start_point')
          %th
            = t('activerecord.attributes.order.end_point')
      %tbody
        - for order in @model
          %tr.body
            %th
              = order.id
            %th
              = order.client_name
            %th
              +375-#{order.client_phone}
            %th
              = order.start_point
            %th
              = order.end_point

app/views/orders/index.html.haml
%section.orders_table
  .col-md-12
    .container
      %h1.text-center
        = t('orders')
        %h5.text-center#notice= notice
        %h5.text-center#alert= alert
        %h5
          = link_to t('send_orders'), send_orders_mail_path, style: 'float: right'
          %br/
          = link_to t('get_pdf'), generate_orders_pdf_path(format: :pdf), style: 'float: right', target: '_blank'
      #{ link_to t('new_order'), new_order_path, class: 'btn btn-outline-info'}
    .row
      .col-md-12
        #orders= render 'orders'
%footer.text-center.footer-order
  .footer-top
    .container
      .row
        .footer-col.col-md-6
          %h6
            = link_to t('affiliates'), affiliates_path
        .footer-col.col-md-6
          %h6
            = link_to t('about_us'),about_path
  .footer-below
    .container
      .row
        .col-md-12
          = t('rights')

app/views/orders/new.html.haml
%section.client_order.sessions-new
  .text-center
    .container
      %h2.order-pad-top
        = t('new_order')
      = render 'form', order: @order
%footer.text-center.footer-order
  .footer-top
    .container
      .row
        .footer-col.col-md-6
          %h6
            = link_to t('affiliates'), affiliates_path
        .footer-col.col-md-6
          %h6
            = link_to t('about_us'),about_path
  .footer-below
    .container
      .row
        .col-md-12
          = t('rights')

app/views/orders/pdf_orders.pdf.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
    = wicked_pdf_stylesheet_link_tag 'pdf'
  %body
    %h1
      = t('orders_report')
    %h3.color-text
      = t('greeting', user_first_name: @user.first_name, user_last_name: @user.last_name)
    %table
      %thead
        %tr.head
          %th #
          %th
            = t('activerecord.attributes.order.name')
          %th
            = t('activerecord.attributes.order.phone')
          %th
            = t('activerecord.attributes.order.start_point')
          %th
            = t('activerecord.attributes.order.end_point')
      %tbody
        - for order in @orders
          %tr.body
            %th
              = order.id
            %th
              = order.client_name
            %th
              +375-#{order.client_phone}
            %th
              = order.start_point
            %th
              = order.end_point

app/views/orders/show.html.haml
%section.orders_table.text-center.order-show
  .row.justify-content-md-center
    .col-md-4
      .container
        %h4
          =t('activerecord.models.order')
        %ul.list-group
          %li.list-group-item
            %b
              #{t('name')}:
            = @model.client_name
          %li.list-group-item
            %b
              #{t('activerecord.attributes.user.phone')}:
            +375-#{@model.client_phone}
          %li.list-group-item
            %b
              #{t('activerecord.attributes.order.start_point')}:
            = @model.start_point
          %li.list-group-item
            %b
              #{t('activerecord.attributes.order.end_point')}:
            = @model.end_point

        -unless @model.invoice.nil?
          %li.list-group-item
            %b
              #{t('activerecord.models.invoice')}:
            #{@model.invoice.distance},
            =@model.invoice.invoice_status.title
      = link_to t('edit_order'), edit_order_path(@model.id), class: 'btn btn-outline-success'
      %div/
      = link_to t('back'), orders_path
%footer.text-center.footer-order
  .footer-top
    .container
      .row
        .footer-col.col-md-6
          %h6
            = link_to t('affiliates'), affiliates_path
        .footer-col.col-md-6
          %h6
            = link_to t('about_us'),about_path
  .footer-below
    .container
      .row
        .col-md-12
          = t('rights')

    %footer.text-center.footer-order
      .footer-top
        .container
          .row
            .footer-col.col-md-6
              %h6
                = link_to t('affiliates'), affiliates_path, style: 'color: #ffc107'
            .footer-col.col-md-6
              %h6
                = link_to t('about_us'),about_path, style: 'color: #ffc107'
      .footer-below
        .container
          .row
            .col-md-12
              = t('rights')