config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get 'orders/send_email_with_orders',
      to: 'orders#send_email_with_orders',
      as: :send_orders_mail
  get 'orders/generate_orders_pdf',
      to: 'orders#generate_orders_pdf',
      as: :generate_orders_pdf
  get 'feedback', to: 'home#feedback_mail', as: :feedback
  post '', to: 'home#feedback_mail', as: '/'
  root to: 'home#index'
  get '/about', to: 'home#about', as: :about
  resources :affiliates, only: %i[show index]
  resources :orders

  namespace :admin do
    get 'dashboard/index'
    get '', to: 'dashboard#index', as: '/'
    resources :users
    resources :affiliates do
      get 'show_workers',
          to: 'affiliates#show_workers',
          as: :show_workers
    end
    resources :taxes, except: :show
    get 'taxes/default_tax_selection', to: 'taxes#default_tax_selection',
                                       as: :default_tax_selection
    post 'taxes/set_default', to: 'taxes#set_default',
                              as: :set_default_tax_post
    resources :cars
    resources :user, controller: 'admin/users'
    resources :order_statuses, only: [:index]
    resources :orders do
      resources :invoices, only: %i[new create edit update]
      resource :car_assignment, only: %i[new create edit update]
    end
  end
  match '*path', to: 'home#routing_error', via: %i[get post put delete]
end

app/models/affiliate.rb
# Affiliate model class
class Affiliate < Sequel::Model
  one_to_many :cars
  one_to_many :users
end

app/controllers/admin/affiliates_controller.rb
module Admin
  #
  class AffiliatesController < AdminController
    def index
      result = Admin::Affiliate::Index.call(params: params,
                                            current_user: current_user)
      handle_successful(result)
    end

    def new
      result = Admin::Affiliate::Create::Present.call(params: params,
                                                      current_user:
                                                          current_user)
      handle_successful(result)
    end

    def create
      result = Admin::Affiliate::Create.call(params: params,
                                             current_user: current_user)
      handle_successful(result) do
        redirect_to admin_affiliates_path,
                    notice: t('affiliate_created', affiliate_name: @model.name)
      end
      handle_invalid(result) do
        render :new
      end
    end

    def show
      result = Admin::Affiliate::Show.call(params: params,
                                           current_user: current_user)
      handle_successful(result)
    end

    def edit
      result = Admin::Affiliate::Update::Present.call(params: params,
                                                      current_user:
                                                          current_user)
      handle_successful(result)
    end

    def update
      result = Admin::Affiliate::Update.call(params: params,
                                             current_user: current_user)
      handle_successful(result) do
        redirect_to admin_affiliates_path,
                    notice: t('affiliate_created', affiliate_name: @model.name)
      end
      handle_invalid(result) do
        render :edit
      end
    end

    def destroy
      result = Admin::Affiliate::Delete.call(params: params,
                                             current_user: current_user)
      handle_successful(result) do
        redirect_to admin_affiliates_path,
                    notice: t('affiliate_deleted', affiliate_name: @model.name)
      end
    end

    def show_workers
      result = Admin::Affiliate::ShowWorkers.call(params: params,
                                                  current_user:
                                                               current_user)
      handle_successful(result) do
        @workers = result['workers']
      end
    end

    protected

    def not_found_redirect_path
      admin_affiliates_path
    end
  end
end

app/controllers/affiliates_controller.rb
class AffiliatesController < ApplicationController

  def index
    run Affiliate::Index
  end

  def show
    run Affiliate::Show
  end
end

app/views/admin/affiliates/_form.html.haml
- if @form.errors.any?
  .error
    %h5.text-center
      = t('error')
      - @form.errors.full_messages.each do |message|
        %h6.text-center
          &#9899; #{message}


= form_for [:admin, @model] do |form|
  .row.justify-content-md-center.text-center
    .col-md-4
      .order_form_area
        .form-group
          = form.label :name
          = form.text_field :name, class: 'form-control'
        .form-group
          = form.label :address
          = form.text_field :address, class: 'form-control'
        .actions
          = form.submit t('submit'), class: 'btn btn-primary'
          = link_to t('back'), admin_affiliates_path, class: 'btn btn-secondary'

app/views/admin/affiliates/edit.html.haml
%h2.text-center
  = t('edit_affiliate')

= render 'form', affiliate: @model

app/views/admin/affiliates/index.html.haml
%h1
  = t('affiliates')
  = link_to t('create'), new_admin_affiliate_path, class: 'btn btn-outline-info pull-right'
%p#notice
  =notice

%table.table.table-bordered
  %thead
    %tr
      %th #
      %th
        = t('activerecord.models.affiliate')
      %th
        = t('address')
      %th
  %tbody
    - @model.each do |affiliate|
      %tr
        %th
          = affiliate.id
        %td
          .affiliate-name= link_to affiliate.name, admin_affiliate_path(affiliate)
        %td
          = affiliate.address
        %td
          = link_to t('edit'), edit_admin_affiliate_path(affiliate.id), class: 'btn btn-outline-info btn-sm'
          = link_to t('delete'), admin_affiliate_path(affiliate), method: :delete,
                                   data: { confirm: t('confirmation') }, class: 'btn btn-outline-danger btn-sm'

app/views/admin/affiliates/new.html.haml
%h2.text-center
  = t('new_affiliate')

= render 'form', affiliate: @model

app/views/admin/affiliates/show.html.haml
.row.justify-content-md-center.text-center
  .col-sm-4.car-item
    %h2 #{@model.name}
    %h4 #{t('address')}: #{@model.address}
    %h4 #{t('affiliate_personal')}: #{@model.users.count} (#{link_to t('order_info'), admin_affiliate_show_workers_path(@model)})
    = link_to t('edit'), edit_admin_affiliate_path(@model), class: 'btn btn-outline-info btn-sm'
    = link_to t('delete'), admin_affiliate_path(@model), method: :delete, data: { confirm: 'You are sure?' }, class: 'btn btn-outline-danger btn-sm'
    = link_to t('back'), admin_affiliates_path, class: 'btn btn-secondary btn-sm'
%section.car
  - unless @model.cars.empty?
    %h2
      = t('cars')
      = link_to t('new_car'), new_admin_car_path, class: 'btn btn-outline-success pull-right'
    %p#notice= notice
    .row.car-item
      - @model.cars.each do |car|
        - cache car do
          .col-sm-4.car-item
            %ul.list-group
              %li.list-group-item
                %b
                  #{t('activerecord.attributes.car.brand')}:
                = car.brand
              %li.list-group-item
                %b
                  #{t('activerecord.attributes.car.model')}:
                = car.car_model
              %li.list-group-item
                %b
                  #{t('activerecord.attributes.car.reg_number')}:
                = car.reg_number
              %li.list-group-item
                %b
                  #{t('activerecord.attributes.car.color')}:
                = car.color
              %li.list-group-item
                %b
                  #{t('activerecord.attributes.car.style')}:
                = car.style
              %li.list-group-item
                %b
                  #{t('activerecord.attributes.car.affiliate')}:
                = car.affiliate.name
              %li.list-group-item
                %b
                  #{t('activerecord.attributes.car.status')}:
                = t("car_status.#{car.car_status}")
            = link_to t('edit'), edit_admin_car_path(car), class: 'btn btn-outline-info btn-sm'
            = link_to t('delete'), admin_car_path(car), method: :delete, data: { confirm: t('confirmation') }, class: 'btn btn-outline-danger btn-sm'

app/views/admin/affiliates/show_affiliate_workers.html.haml
%h1.text-center #{@model.name}
%h3.text-center #{t('affiliate_personal_list')}
%table.table
  %thead.thead-inverse
    %tr
      %th #
      %th
        = t('activerecord.attributes.user.first_name')
      %th
        = t('activerecord.attributes.user.last_name')
      %th
        = t('activerecord.attributes.user.phone')
      %th Email
      %th
        = t('activerecord.attributes.user.role')
      %th
  %tbody
    - for worker in @workers
      %tr
        %th
          = worker.id
        %th
          = worker.first_name
        %th
          = worker.last_name
        %th
          +375-#{worker.phone}
        %th
          = worker.email
        %th
          #{t("role.#{worker.role}")}
        %th
          = link_to t('edit'), edit_admin_user_path(worker.id), class: 'btn btn-outline-info btn-sm'
          = link_to t('delete'), admin_user_path(worker), method: :delete, data: { confirm: t('confirmation') }, class: 'btn btn-outline-danger btn-sm'

app/views/admin/affiliates/show_workers.html.haml
%h1.text-center #{@model.name}
%h3.text-center #{t('affiliate_personal_list')}
%table.table
  %thead.thead-inverse
    %tr
      %th #
      %th
        = t('activerecord.attributes.user.first_name')
      %th
        = t('activerecord.attributes.user.last_name')
      %th
        = t('activerecord.attributes.user.phone')
      %th Email
      %th
        = t('activerecord.attributes.user.role')
      %th
  %tbody
    - for worker in @workers
      %tr
        %th
          = worker.id
        %th
          = worker.first_name
        %th
          = worker.last_name
        %th
          +375-#{worker.phone}
        %th
          = worker.email
        %th
          #{t("role.#{worker.role}")}
        %th
          = link_to t('edit'), edit_admin_user_path(worker.id), class: 'btn btn-outline-info btn-sm'
          = link_to t('delete'), admin_user_path(worker), method: :delete, data: { confirm: t('confirmation') }, class: 'btn btn-outline-danger btn-sm'