config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get 'orders/send_email_with_orders',
      to: 'orders#send_email_with_orders',
      as: :send_orders_mail
  get 'orders/generate_orders_pdf',
      to: 'orders#generate_orders_pdf',
      as: :generate_orders_pdf
  get 'feedback', to: 'home#feedback_mail', as: :feedback
  post '', to: 'home#feedback_mail', as: '/'
  root to: 'home#index'
  get '/about', to: 'home#about', as: :about
  resources :affiliates, only: %i[show index]
  resources :orders

  namespace :admin do
    get 'dashboard/index'
    get '', to: 'dashboard#index', as: '/'
    resources :users
    resources :affiliates do
      get 'show_workers',
          to: 'affiliates#show_workers',
          as: :show_workers
    end
    resources :taxes, except: :show
    get 'taxes/default_tax_selection', to: 'taxes#default_tax_selection',
                                       as: :default_tax_selection
    post 'taxes/set_default', to: 'taxes#set_default',
                              as: :set_default_tax_post
    resources :cars
    resources :user, controller: 'admin/users'
    resources :order_statuses, only: [:index]
    resources :orders do
      resources :invoices, only: %i[new create edit update]
      resource :car_assignment, only: %i[new create edit update]
    end
  end
  match '*path', to: 'home#routing_error', via: %i[get post put delete]
end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
    %title
      = t('title')
    = csrf_meta_tags
    = stylesheet_link_tag    'admin/dashboard', media: 'all'
    = javascript_include_tag 'admin/admin', media: 'all'
  %body.fixed-nav.sticky-footer
    %nav#mainNav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top
      %a.navbar-brand{href: admin_dashboard_index_path}
        = t('title')
      %button.navbar-toggler.navbar-toggler-right{'aria-controls': 'navbarResponsive', 'aria-expanded': 'false', 'aria-label': 'Toggle navigation', 'data-target': '#navbarResponsive', 'data-toggle': 'collapse', type: 'button'}
        %span.navbar-toggler-icon
      #navbarResponsive.collapse.navbar-collapse
        %ul.navbar-nav.ml-auto
          %li.nav-item.nav-link{class: 'active'}
            #{current_user.first_name}  #{current_user.last_name} :
          %li.nav-item
            = link_to t('edit'),edit_admin_user_path(current_user.id), class: 'nav-link'
          %li.nav-item
            = link_to destroy_user_session_path, method: :delete, data: { confirm: t('confirmation') }, class: 'nav-link' do
              %i.fa.fa-fw.fa-sign-out
              = t('sign_out')
    .sidenav
      %ul.navbar-nav.navbar-sidenav
        %li.sidenav-item
          - if current_user.role.in?(%w[Admin Manager Driver Dispatcher])
            = link_to t('orders'), admin_orders_path
            = link_to t('taxes'), admin_taxes_path
          - if current_user.role.in?(%w[Admin Manager])
            = link_to t('users'), admin_users_path
        %li.sidenav-item
          - if current_user.role.in?(%w[Admin Manager Dispatcher])
            = link_to t('cars'), admin_cars_path
        %li.sidenav-item
          - if current_user.role == 'Admin'
            = link_to t('affiliates'), admin_affiliates_path

    .content-wrapper
      .container-fluid
        = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
      = t('title')
    %title
      = t('title')
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    .navbar.navbar-dark.navbar-expand-lg.fixed-top.navbar-collapse#mainNav
      %a.navbar-brand#page-top{href: root_path ,style: 'color: #ffc107'}
    .navbar.navbar-dark.bg-primary.navbar-expand-md
      %a.navbar-brand{href: root_path}
        = t('title')
      %button.navbar-toggler{'aria-controls': 'main-menu', 'aria-expanded': 'false', 'aria-label': 'Toggle navigation', 'data-target': "#main-menu", "data-toggle": "collapse", type: "button"}
        %span.navbar-toggler-icon
      #main-menu.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item.active
            %a.nav-link{href: "#{affiliates_path}"}
              = t('affiliates')
          %li.nav-item.active
            - if user_signed_in?
              - if current_user.try(:client?)
                %a.nav-link{href: "#{new_order_path}"}
                  = t('new_order')
              -else
                %a.nav-link{href: "#{new_admin_order_path}"}
                  = t('new_order')
            - else
              %a.nav-link{href: "#{new_user_session_path}", }
                = t('new_order')
          - if user_signed_in?
            %li.nav-item
              -if current_user.try(:client?)
                %a.nav-link{href: "#{orders_path}"}
                  = t('orders')
              -else
                %a.nav-link{href: "#{admin_orders_path}"}
                  = t('orders')
        - if user_signed_in?
          %a.navbar-brand{style:'color:yellow'}
            = t('signed_in')
          %a.navbar-brand{style:'color:white'} #{current_user.first_name} #{current_user.last_name}
          = link_to t('edit'),edit_user_registration_path, class: 'btn btn-success'
          = link_to t('sign_out'),destroy_user_session_path, method: :delete, class: 'btn btn-danger'
        -else
          .login
            = link_to t('sign_in'), new_user_session_path, class: 'btn btn-success'
            = link_to t('sign_up'), new_user_registration_path, class: 'btn btn-warning'

    .container.pad-top
      %p#notice= notice
      %p#alert= alert
      = yield

app/views/layouts/page.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
    %title
      = t('title')
    = csrf_meta_tags
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = favicon_link_tag 'tab.gif'
  %body
    .navbar.navbar-dark.navbar-expand-lg.fixed-top.navbar-collapse#mainNav
      %a.navbar-brand#main-link{href: root_path}
        = t('title')
      %button.navbar-toggler{'aria-controls': 'main-menu', 'aria-expanded': 'false', 'aria-label': 'Toggle navigation', 'data-target': '#main-menu', "data-toggle": "collapse", type: 'button'}
        %span.navbar-toggler-icon
      #main-menu.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item
            - if user_signed_in?
              - if current_user.role == 'Client'
                %a.nav-link.extra-link{href: "#{new_order_path}"}
                  = t('new_order')
              -else
                %a.nav-link.extra-link{href: "#{new_admin_order_path}"}
                  = t('new_order')
          - if user_signed_in?
            %li.nav-item
              -if current_user.role == 'Client'
                %a.nav-link.extra-link{href: "#{orders_path}"}
                  = t('orders')
              -else
                %a.nav-link.extra-link{href: "#{admin_orders_path}"}
                  = t('orders')
        - if user_signed_in?
          .user-signed{style:'color:#ffc107'}
            = t('signed_in')
          .user-signed{style:'color:white'} #{current_user.first_name} #{current_user.last_name}
          = link_to t('edit'),edit_user_registration_path, class: 'btn btn-size btn-success'
          = link_to t('sign_out'),destroy_user_session_path, data: { confirm: t('confirmation') }, method: :delete, class: 'btn btn-size btn-danger'
        -else
          .login
            = link_to t('sign_in'), new_user_session_path, class: 'btn btn-size btn-success'
            = link_to t('sign_up'), new_user_registration_path, class: 'btn btn-size btn-info'

    = yield